// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juxpvvpogpolspxnecsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1eHB2dnBvZ3BvbHNweG5lY3NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTA5OTIsImV4cCI6MjA3MDI4Njk5Mn0.sWhfCj4wT2pa3sU9o5kiE5lVhm67Emxft7eTA4qkdtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});