name: DB Verify and Backup

on:
  workflow_dispatch: {}
  push:
    branches:
      - test/kanban-validation

jobs:
  verify-and-backup:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check required secrets
        if: env.SUPABASE_DB_URL == ''
        run: |
          echo "Missing required secret SUPABASE_DB_URL." >&2
          echo "Add it in Settings → Secrets and variables → Actions." >&2
          exit 1

      - name: Install PostgreSQL client (pg_dump/psql)
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Check DB connectivity
        run: |
          psql "$SUPABASE_DB_URL" -c "select current_user, now();"

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: List migrations (remote vs local)
        if: env.SUPABASE_DB_URL != ''
        run: |
          supabase migration list \
            --db-url "$SUPABASE_DB_URL" \
            --workdir ./supabase | tee migration_status.txt
          {
            echo "# Migration Status";
            echo "";
            echo '\`\`\`';
            cat migration_status.txt;
            echo '\`\`\`';
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Dump database via pg_dump (full SQL)
        if: env.SUPABASE_DB_URL != ''
        env:
          PGCONNECT_TIMEOUT: "20"
        run: |
          mkdir -p backups
          # Dump em formato SQL plano para fácil restauração com psql
          pg_dump "$SUPABASE_DB_URL" \
            --no-owner --no-privileges --verbose \
            --file backups/${{ github.run_id }}_full.sql

      - name: Compress backup
        if: env.SUPABASE_DB_URL != ''
        run: |
          gzip -9 backups/${{ github.run_id }}_full.sql

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: db-artifacts-${{ github.run_id }}
          path: |
            migration_status.txt
            backups/*.sql.gz
