name: Bootstrap Actions

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print context
        run: |
          echo "Workflow bootstrapped at $(date -u)"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
